default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Dungoneer_development

test:
  <<: *default
  database: Dungoneer_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: Dungoneer_production
  username: Dungoneer
  password: <%= ENV['Dungoneer_DATABASE_PASSWORD'] %>
